on: [push]

name: AzureARMDeploy

jobs:
  deploy: 
  runs-on: ubuntu-latest
  steps:
   
   - name: login to azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: checkout source code
      uses: actions/checkout@v2

    - name: deploy ARM template
        uses: azure/CLI@v1
  with:
    inlineScript: |
      az deployment group create
      --name StorageAccountDeployment \
      --resource-group savdevgithubdeploy \
      --template-file armtemplates/storageaccount.json \
      --parameters storageAccountType=Standard_GRS


